[ { Title: 'Atlanta Braves GM1 L Sims -R',
hour: '4:10 PM',
Teams: [ [Object], [Object] ] },
{ Title: 'Washington Nationals A J Cole -R',
hour: '7:05 PM',
Teams: [ [Object], [Object] ] },
{ Title: 'Atlanta Braves GM2 M Fried -L',
hour: '7:10 PM',
Teams: [ [Object], [Object] ] },
{ Title: 'Chicago Cubs J Lester -L',
hour: '8:15 PM',
Teams: [ [Object], [Object] ] },
{ Title: 'Miami Marlins O Despaigne -R',
hour: '8:40 PM',
Teams: [ [Object], [Object] ] },
{ Title: 'San Diego Padres Tr Wood -L',
hour: '10:10 PM',
Teams: [ [Object], [Object] ] },
{ Title: 'Kansas City Royals J Junis -R',
hour: '1:05 PM | (TM CH)',
Teams: [ [Object], [Object] ] },
{ Title: 'Toronto Blue Jays B Anderson -L',
hour: '7:10 PM',
Teams: [ [Object], [Object] ] },
{ Title: 'Houston Astros C McHugh -R',
hour: '8:05 PM',
Teams: [ [Object], [Object] ] },
{ Title: 'Los Angeles Angels R Nolasco -R',
hour: '8:10 PM',
Teams: [ [Object], [Object] ] },
{ Title: 'Seattle Mariners F Hernandez -R',
hour: '10:05 PM',
Teams: [ [Object], [Object] ] },
{ Title: 'Atlanta Braves GM 1 L Sims -R',
hour: '4:10 PM | Game must go 8½ innings if home team is winning or 9 innings if road team is winning for action.',
Teams: [ [Object], [Object] ] },
{ Title: 'Washington Nationals A J Cole -R',
hour: '7:05 PM | Game must go 8½ innings if home team is winning or 9 innings if road team is winning for action.',
Teams: [ [Object], [Object] ] },
{ Title: 'Washington Nationals A J Cole -R',
hour: '7:05 PM | Game must go 8½ innings if home team is winning or 9 innings if road team is winning for action.',
Teams: [ [Object], [Object] ] },
{ Title: 'Atlanta Braves GM 2 M Fried -L',
hour: '7:10 PM | Game must go 8½ innings if home team is winning or 9 innings if road team is winning for action.',
Teams: [ [Object], [Object] ] },
{ Title: 'Atlanta Braves GM 2 M Fried -L',
hour: '7:10 PM | Game must go 8½ innings if home team is winning or 9 innings if road team is winning for action.',
Teams: [ [Object], [Object] ] },
{ Title: 'Chicago Cubs J Lester -L',
hour: '8:15 PM | Game must go 8½ innings if home team is winning or 9 innings if road team is winning for action.',
Teams: [ [Object], [Object] ] },
{ Title: 'Chicago Cubs J Lester -L',
hour: '8:15 PM | Game must go 8½ innings if home team is winning or 9 innings if road team is winning for action.',
Teams: [ [Object], [Object] ] },
{ Title: 'Miami Marlins O Despaigne -R',
hour: '8:40 PM | Game must go 8½ innings if home team is winning or 9 innings if road team is winning for action.',
Teams: [ [Object], [Object] ] },
{ Title: 'Miami Marlins O Despaigne -R',
hour: '8:40 PM | Game must go 8½ innings if home team is winning or 9 innings if road team is winning for action.',
Teams: [ [Object], [Object] ] },
{ Title: 'San Diego Padres Tr Wood -L',
hour: '10:10 PM | Game must go 8½ innings if home team is winning or 9 innings if road team is winning for action.',
Teams: [ [Object], [Object] ] },
{ Title: 'San Diego Padres Tr Wood -L',
hour: '10:10 PM | Game must go 8½ innings if home team is winning or 9 innings if road team is winning for action.',
Teams: [ [Object], [Object] ] },
{ Title: 'Kansas City Royals J Junis -R',
hour: '1:05 PM | Game must go 8½ innings if home team is winning or 9 innings if road team is winning for action.',
Teams: [ [Object], [Object] ] },
{ Title: 'Kansas City Royals J Junis -R',
hour: '1:05 PM | Game must go 8½ innings if home team is winning or 9 innings if road team is winning for action.',
Teams: [ [Object], [Object] ] },
{ Title: 'Toronto Blue Jays B Anderson -L',
hour: '7:10 PM | Game must go 8½ innings if home team is winning or 9 innings if road team is winning for action.',
Teams: [ [Object], [Object] ] },
{ Title: 'Toronto Blue Jays B Anderson -L',
hour: '7:10 PM | Game must go 8½ innings if home team is winning or 9 innings if road team is winning for action.',
Teams: [ [Object], [Object] ] },
{ Title: 'Houston Astros C McHugh -R',
hour: '8:05 PM | Game must go 8½ innings if home team is winning or 9 innings if road team is winning for action.',
Teams: [ [Object], [Object] ] },
{ Title: 'Houston Astros C McHugh -R',
hour: '8:05 PM | Game must go 8½ innings if home team is winning or 9 innings if road team is winning for action.',
Teams: [ [Object], [Object] ] },
{ Title: 'Los Angeles Angels R Nolasco -R',
hour: '8:10 PM | Game must go 8½ innings if home team is winning or 9 innings if road team is winning for action.',
Teams: [ [Object], [Object] ] },
{ Title: 'Los Angeles Angels R Nolasco -R',
hour: '8:10 PM | Game must go 8½ innings if home team is winning or 9 innings if road team is winning for action.',
Teams: [ [Object], [Object] ] },
{ Title: 'Seattle Mariners F Hernandez -R',
hour: '10:05 PM | Game must go 8½ innings if home team is winning or 9 innings if road team is winning for action.',
Teams: [ [Object], [Object] ] },
{ Title: 'Seattle Mariners F Hernandez -R',
hour: '10:05 PM | Game must go 8½ innings if home team is winning or 9 innings if road team is winning for action.',
Teams: [ [Object], [Object] ] } ]